name: Linux Waydroid (24/7)

on:
  workflow_dispatch:  # Allows manual run from GitHub UI
  schedule:
    - cron: "0 */6 * * *"  # Optional auto-restart every 6 hours

jobs:
  waydroid:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore previous session data
        uses: actions/download-artifact@v4
        with:
          name: waydroid-data
          path: $HOME/waydroid-data
        continue-on-error: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl lxc wget sudo
          sudo apt install -y dbus-user-session git unzip

      - name: Install Waydroid
        run: |
          sudo curl -s https://repo.waydro.id | sudo bash
          sudo apt install -y waydroid

      - name: Initialize Waydroid
        run: |
          sudo waydroid init
          sudo systemctl start waydroid-container
          sudo systemctl enable waydroid-container
          sleep 10
          waydroid status

      - name: Install Tailscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt update
          sudo apt install -y tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-waydroid-vm

      - name: Get Tailscale IP
        run: |
          IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$IP" >> $GITHUB_ENV
          echo "Access Waydroid VM via Tailscale: $IP"

      - name: Keep workflow alive
        run: |
          while true; do
            echo "Waydroid VM running at $TAILSCALE_IP"
            sleep 300
          done

      - name: Save Waydroid data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: waydroid-data
          path: $HOME/waydroid-data
